### ISSUE TITLE
Fallen links

### ISSUE THREAD

**Issue by adrianRodriguez123** [the-raspberry-pi-guy/skateboard#3]
Hey man. I love this project but check your links in the readme file. The "4 x Alien 83mm longboard wheels" and "Raspberry Pi Power: Buck 5v converter" are fallen. Please update all the links that need it. Thank you ;)

**Comment by the-raspberry-pi-guy** [comment]
Hey!

Thanks for pointing this out. Some of the shops I got those parts from now no longer trade or have updated their websites. I have updated the links to other retailers!

Thanks again
