### ISSUE TITLE
wiimote/esc error/calibration?

### ISSUE THREAD

**Issue by mooneypadfoot** [the-raspberry-pi-guy/skateboard#4]
Hi! I was inspired by your build and attempted to recreate it (with slightly different specs), i loaded your code on to my pi (with the led parts erased as i didn't use them) but the esc doesn't seem to respond. it didn't have the initial beeps after powering on. I believe there are no errors in the code as Python2 was able to run it. Did you run into similar problems during your build?? Thank you for your help!

**Comment by the-raspberry-pi-guy** [comment]
Hey!

Awesome that you were inspired! What ESC do you have? All of them are different models and so, while their general principle is the same, they'll all behave slightly differently. You control them using a PWM signal (which I do in Python), but you might find that the PWM signals you have to send yours are a little bit different.

You should consult the documentation for your ESC. There was hardly any documentation for mine - so I found mine out through a combination of guesswork and trying values!

Thanks

**Comment by mooneypadfoot** [comment]
I'm using a HobbyKing 120a X-beast series ESC. I was able find a manual but it lacked information on PWM signals. I'll try various signals! Thanks again! :) :) :)

**Comment by the-raspberry-pi-guy** [comment]
Let me know how it goes! I'll close this issue now. Thanks
